### ISSUE TITLE
panic: Your platform is unsupported! I can't clear terminal screen :(

### ISSUE THREAD

**Issue by hassankhan98** [M4DM0e/DirDar#1]
panic: Your platform is unsupported! I can't clear terminal screen :(

Screen shot = https://ibb.co/Qb96ZYX

any solution

**Comment by M4DM0e** [comment]
Hi @hassankhan98,
Please download the source again and compile it then let me know if the problem still.

**Comment by M4DM0e** [comment]
I've made a temporary fix till I update the whole source

**Comment by 779789571** [comment]
The same problem appeared on my mac. I downloaded the source code and compiled it and still couldn’t solve the problem.

**Comment by 779789571** [comment]
> The same problem appeared on my mac. I downloaded the source code and compiled it and still couldn’t solve the problem.

I commented out the code about scre3n(), recompile it and it will run normally:)
