### ISSUE TITLE
How to use winx64

### ISSUE THREAD

**Issue by 2077himasi** [M4DM0e/DirDar#4]
dirdar  1.txt -only-ok
report errors
![image](https://user-images.githubusercontent.com/31888299/109413483-9985fa00-79e8-11eb-8627-cae0f4985ccd.png)
![image](https://user-images.githubusercontent.com/31888299/109413496-ad316080-79e8-11eb-909b-d738c6a04cf7.png)

**Comment by M4DM0e** [comment]
type 1.txt | dirdar.exe -err

![windows](https://github.com/M4DM0e/DirDar/assets/33535839/17ade7b0-6f2f-441c-9919-bb30023a6f91)

sorry for the delayed reply!

**Comment by M4DM0e** [comment]
Closing this.
