### ISSUE TITLE
panic: Your platform is unsupported! I can't clear terminal screen :(

### ISSUE THREAD

**Issue by N0o01** [M4DM0e/DirDar#8]
➜  dirdar cat ip.txt | ./dirdar -err  
panic: Your platform is unsupported! I can't clear terminal screen :(

goroutine 1 [running]:
main.scre3n(...)
	/home/ali/t00ls/DirDar/main.go:71
main.bann3r()
	/home/ali/t00ls/DirDar/main.go:307 +0x242
main.main()
	/home/ali/t00ls/DirDar/main.go:330 +0x34

**Comment by mrberbles** [comment]
**Here are steps to address the "unsupported platform" error and achieve terminal clearing:**

**1. Identify Your Platform:**

- **Windows:** Use `cls` to clear the screen.
- **Linux and macOS:** Use `clear` to clear the screen.
- **Other platforms:** Consult documentation or online resources for specific commands or methods.

**2. Modify the Code (if applicable):**

- If you have access to the code, use conditional statements to check the platform and execute the appropriate command:

   ```python
   import os

   if os.name == "nt":  # Windows
       os.system("cls")
   else:  # Linux, macOS, or other
       os.system("clear")
   ```

**3. Explore Alternative Methods:**

- **Manual Clearing:**
   - **Windows:** Use the shortcut `Ctrl+L`.
   - **Linux and macOS:** Use the shortcut `Ctrl+L` or `Cmd+K` (in some terminals).
- **Terminal Settings:**
   - Some terminals offer options to clear the screen within their menus or settings.
- **External Libraries:**
   - Consider using platform-independent libraries like `termios` for advanced terminal control.

**Additional Considerations:**

- **Error Context:** If possible, share more details about the specific error, program, and platform for tailored advice.
- **Code Modification:** If you're comfortable with code, provide relevant snippets for further guidance.
